### ISSUE TITLE
SetMuse typo sending wrong command

### ISSUE THREAD

**Issue by jonhaag** [roy86/HumanCyborgRelationsAPI#4]
In HCR.cpp:

void HCRVocalizer::SetMuse(int v) {
    if (v < 0 || v > 1) return;
    **String msg = "O" + ToString(v) + ",QM";**
    sendCommand(msg);
}
 
should be 

void HCRVocalizer::SetMuse(int v) {
    if (v < 0 || v > 1) return;
    **String msg = "M" + ToString(v) + ",QM";**
    sendCommand(msg);
}

**Comment by roy86** [comment]
Good catch. Fixed and pushed the update
